### ISSUE TITLE
Fix 'HPE_INVALID_HEADER_TOKEN' error

### ISSUE THREAD

**Issue by ishqbb** [ishqbb/morrolantv-api#12]
- [x] create regression test

<pre>
$ node scripts/nodejs-bdoclient-GetWorldMarketList.js
{ RequestError: Parse Error
    at /morrolantv-api/src/utils/makeTransformError.js:48:11
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RequestError',
  details:
   { method: 'post',
     url: 'GetWorldMarketList',
     reason: undefined,
     message: 'Parse Error',
     config:
      '{"url":"GetWorldMarketList","method":"post","data":"{\\"mainCategory\\":1,\\"subCategory\\":1,\\"keyType\\":0}","headers":{"Content-Type":"application/json","User-Agent":"BlackDesert","Content-Length":46},"baseURL":"https://na-trade.naeu.playblackdesert.com/Trademarket","transformRequest":[null],"transformResponse":[null],"timeout":2500,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"httpsAgent":{"_events":{},"_eventsCount":0,"timeout":null,"maxFreeSockets":1,"maxSockets":1,"maxTotalSockets":null,"sockets":{},"freeSockets":{},"requests":{},"options":{},"lookup":true,"proxy":{"host":"127.0.0.1","port":7770,"type":5}},"retries":3}',
     headers:
      { 'Content-Type': 'application/json',
        'User-Agent': 'BlackDesert',
        'Content-Length': 46 },
     stack:
      'Error: Parse Error\n    at TLSSocket.socketOnData (_http_client.js:451:20)\n    at TLSSocket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at TLSSocket.Readable.push (_stream_readable.js:224:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)',
     code: 'HPE_INVALID_HEADER_TOKEN' } }
</pre>

**Comment by ishqbb** [comment]
Using `node --insecure-http-parser  scripts/nodejs-bdoclient-GetWorldMarketList.js` fixes the issue but is an unacceptable solution.

**Comment by ishqbb** [comment]
[nodejs/http-parser](https://github.com/nodejs/http-parser)/http_parser.c might provide some insight.

https://github.com/nodejs/http-parser/blob/ec8b5ee63f0e51191ea43bb0c6eac7bfbff3141d/http_parser.c#L1583

**Comment by ishqbb** [comment]
https://github.com/nodejs/llhttp is the current library used by node. 
https://github.com/nodejs/llhttp/blob/ea39835754c9cc1820262c77e4ccb176cf4356be/src/llhttp/http.ts#L425

**Comment by ishqbb** [comment]
<pre>
$> node --version
v10.19.0
</pre>

**Comment by ishqbb** [comment]
Upgraded node to v14.1.1.

Closing the issue for now since the issue was popping-up intermittently and I was using an outdated version of node that was used by Ubuntu 20.04. LTS.

**Comment by ishqbb** [comment]
Updating node did not alleviate issue, as it has now shown up again.

**Comment by ishqbb** [comment]
It was incorrectly being classified as a `request.error`. The issue occurs when the remote API responds with the following response: 

<pre>
HTTP/1.1 200 OK
Date: Wed, 07 Apr 2021 22:33:18 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 5303
Connection: close
Cache-Control: private
Access-Control-Allow-Origin: https://na-trade.naeu.playblackdesert.com
Access-Control-Allow-Credentials: true
Set-Cookie: visid_incap_2504212=/+zcmqGWQguRcJF2dugJvaEybmAAAAAAQUIPAAAAAADl8Iy52xh/nrwo36pzt7bf; expires=Thu, 07 Apr 2022 08:21:23 GMT; HttpOnly; path=/; Domain=.naeu.playblackdesert.com; Secure; SameSite=None
Set-Cookie: nlbi_2504212=k7qOFoi5zhhhJlxOAX4icwAAAACVVkgMgpR5x8abZNCGOZPN; path=/; Domain=.naeu.playblackdesert.com; Secure; SameSite=None
Set-Cookie: incap_ses_1163_2504212=io8IVvEi/yjKBCUwms4jEC0zbmAAAAAA0PCeXRvjX+sdrCv5Sweekw==; path=/; Domain=.naeu.playblackdesert.com; Secure; SameSite=None
Set-Cookie: ___utmvmvFBuKalvZ=DhVRoTKhHOM; path=/; Max-Age=900; Secure; SameSite=None
Set-Cookie: ___utmvavFBuKalvZ=lqSKyIE; path=/; Max-Age=900; Secure; SameSite=None
Set-Cookie: ___utmvbvFBuKalvZ=dZd
    XMJOHalg: RtP; path=/; Max-Age=900; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000
X-CDN: Imperva
X-Iinfo: 7-76703977-76703981 NNNY CT(0 0 0) RT(1617834797057 69) q(0 0 0 0) r(6 6) U5

{"resultCode":0,"resultMsg":"10003-0-57488-16900|10005-7-608508-32800|10006-0-113996-292000|10007-0-315594-89500|10009-37-103499-5050000|10010-10-40305-184000000|10012-6-582460-75000|10013-3-700529-63000|10014-44-1085548-156000|10056-6-731908-34
</pre>

**Comment by ishqbb** [comment]
Testing was implemented via c2efffccffab798263bb41677655253260c9328d

The solution for this issue is resolved by overriding the axios http request options
<pre>
    const wrappedHttp = {
      ...http,
      request: (options, callback) => http.request({
        ...options,
        insecureHTTPParser: true,
      }, callback),
    };
    const client = axios.create({
      transport: wrappedHttp,
    });
</pre>

import http or https depending on the usage.

**Comment by ishqbb** [comment]
Resolved with 898ed524b69e72607d253ab8a7fd91f046bf02ba
